language: scala
sudo: false
scala:
  - 2.10.5
script: 
  - sbt ++$TRAVIS_SCALA_VERSION test scripted
notifications:
  email:
    recipients:
      - m.aichler@mediacluster.de
jdk:
  - openjdk7
  - oraclejdk7
